taskkill /IM postgres.exe /F
taskkill /IM SAiDownloaderVista.exe /F
taskkill /IM SAiAdmin.exe /F
taskkill /IM multipassd.exe /F
taskkill /IM ForwardDaemon.exe /F
taskkill /IM TeamViewer_Service.exe /F
taskkill /IM MotoHelperService.exe  /F
taskkill /IM sqlwriter.exe  /F
taskkill /IM MotoHelperAgent.exe /F
taskkill /IM SLDWORKS.exe /F
taskkill /IM git-bash.exe /F
taskkill /IM Updater.exe  /F
taskkill /IM chrome.exe /F
taskkill /IM NIWebServiceContainer.exe /F