taskkill /IM /F postgres.exe
taskkill /IM /F SAiDownloaderVista.exe
taskkill /IM /F SAiAdmin.exe 
taskkill /IM /F multipassd.exe 
taskkill /IM /F ForwardDaemon.exe 
taskkill /IM /F TeamViewer_Service.exe 
taskkill /IM /F MotoHelperService.exe  
taskkill /IM /F sqlwriter.exe  
taskkill /IM /F MotoHelperAgent.exe 
taskkill /IM /F SLDWORKS.exe 
taskkill /IM /F git-bash.exe 
taskkill /IM /F Updater.exe  
taskkill /IM /F chrome.exe 
taskkill /IM /F NIWebServiceContainer.exe 